[build-system]
requires = [
    "setuptools>=36.6",
    "packaging",
    "wheel",
    "Cython",
    "qutip@git+https://github.com/qutip/qutip.git", # TODO: 5.2.1 we released
    "numpy",
]
build-backend = "setuptools.build_meta"

# URLs for your project
# [project.urls]
# Homepage = "https://github.com/qutip/qutip-cuquantum"
# "Bug Tracker" = "https://github.com/qutip/qutip-cuquantum/issues"


[tool.pytest.ini_options]
addopts = "-Werror --strict-config --strict-markers -W ignore::DeprecationWarning"
testpaths = [
    "tests",
]
